# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_affected', models.IntegerField()),
                ('affected_area', models.CharField(max_length=50)),
                ('number_of_casualties', models.IntegerField()),
                ('status', models.CharField(choices=[('v', 'verified'), ('p', 'pending'), ('f', 'falseAlarm')], max_length=20)),
                ('affected_age_group', models.CharField(max_length=20)),
            ],
        ),
    ]
