# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healt', '0003_auto_20170204_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='query',
            name='affected_area',
        ),
        migrations.RemoveField(
            model_name='healthofficer',
            name='city',
        ),
        migrations.AlterField(
            model_name='query',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healt.UserProfile'),
        ),
        migrations.AddField(
            model_name='query',
            name='affected_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healt.City'),
        ),
        migrations.AddField(
            model_name='healthofficer',
            name='city',
            field=models.ManyToManyField(to='healt.City'),
        ),
    ]
