# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healt', '0004_auto_20170204_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userProfile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
