# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healt', '0007_auto_20170204_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='verified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
