# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healt', '0008_auto_20170204_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
