# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healt', '0010_auto_20170204_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='precaution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='affected_age_group',
            field=models.CharField(choices=[('Child', 'Child'), ('Teen', 'Teenagers'), ('Adult', 'Adult'), ('Old', 'Old')], max_length=20),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('FalseAlarm', 'FalseAlarm')], max_length=20),
        ),
    ]
